---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eksup-cluster-1-23
  region: us-east-2
  version: "1.23"
managedNodeGroups:
  - name: eksup-managed-ng
    instanceType: t2.large
    minSize: 2
    maxSize: 2
    desiredCapacity: 2
    iam:
      withAddonPolicies:
        externalDNS: true
        certManager: true
addons:
- name: vpc-cni
- name: coredns
- name: kube-proxy
availabilityZones: ['us-east-2a','us-east-2b']