name: 'Tests'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Run Unit Tests
    strategy:
      matrix:
        version: ['3.8', '3.9', '3.10', '3.11']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.version }}

      - name: Cache Poetry
        id: cache-poetry
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/.poetry
          key: poetry-self-tests-${{ matrix.version }}-${{ hashFiles('**/.github/workflows/tests.yml') }}
          restore-keys: poetry-self-tests-${{ matrix.version }}-

      - name: Install Poetry
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          export POETRY_HOME=${{github.workspace}}/.poetry
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py -O
          python install-poetry.py --preview
          rm install-poetry.py

      - name: Add Poetry to $PATH
        run: echo "${{github.workspace}}/.poetry/bin" >> $GITHUB_PATH

      - name: Add poethepoet plugin
        run: poetry self add 'poethepoet[poetry_plugin]'

      - name: Poetry Version
        run: poetry --version

      - name: Check pyproject.toml validity
        run: poetry check --no-interaction

      - name: Cache Dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/.venv
          key: poetry-deps-tests-${{ matrix.version }}-${{ hashFiles('**/poetry.lock') }}
          restore-keys: poetry-deps-tests-${{ matrix.version }}-

      - name: Install Deps
        if: steps.cache-deps.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Run Tests
        run: |
          poetry poe test

      - name: Codecov
        uses: codecov/codecov-action@v3
