name: 'Validating Code install'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GITHUB_PR_NUMBER: ${{github.event.pull_request.number}}

jobs:
  validate-install:
    name: Validating code install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '${{ inputs.python-version }}'

      - name: Setup Dependencies
        uses: './.github/actions/dep-setup'
        with:
          python-version: '3.10'
      - name: Verify install
        run: |
          pip3 install "git+https://github.com/quixoticmonk/eks-cluster-upgrade.git@refs/pull/${{GITHUB_PR_NUMBER}}/head"


